### ISSUE TITLE
error complilation

### ISSUE THREAD

**Issue by styla01** [uakfdotb/ent-ghost#10]
i have stange errors (150) about redefinition in "stdint.h" : 
Error   1   error C2371: 'int8_t' : redefinition; different basic types C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\include\stdint.h 8

and this error x 30 times in "deque"
 Error  38  error C2027: use of undefined type 'HostNameInfo'   C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\include\deque    952
 give me a hint plsease (i have MVS 2012)

**Comment by Profforgr** [comment]
ent-ghost is Linux only.

**Comment by styla01** [comment]
you all time u said somth allready know, pls dont respond again, let uakf to do this, thnks.

**Comment by uakfdotb** [comment]
ent-ghost is Linux only. It is designed for Linux. You can post at ghostpp.com if you want help with compiling, but the issue tracker on GitHub is for actual bugs / suggestions and not simply for help on an unsupported OS.

**Comment by styla01** [comment]
very fast response, ty
delete this.
