### ISSUE TITLE
Not enough file geoip.h 

### ISSUE THREAD

**Issue by TemKaSD** [uakfdotb/ent-ghost#12]
/ent/ent-ghost-luna$ make clean && make
rm -f bncsutilinterface.o bnet.o bnetprotocol.o bnlsclient.o bnlsprotocol.o commandpacket.o config.o crc32.o csvparser.o game.o game_base.o gameplayer.o gameprotocol.o gameslot.o gcbiprotocol.o ghost.o ghostdb.o ghostdbmysql.o gpsprotocol.o language.o map.o packed.o replay.o savegame.o sha1.o socket.o stats.o statsdota.o statsw3mmd.o util.o  ./ghost++
g++ -o bncsutilinterface.o  -O3 -g  -I. -I../bncsutil/src/ -I../StormLib/ -c bncsutilinterface.cpp
In file included from ghost.h:29:0,
                 from bncsutilinterface.cpp:26:
includes.h:51:19: fatal error: GeoIP.h: Нет такого файла или каталога
compilation terminated.
make: **\* [bncsutilinterface.o] Ошибка 1

**Comment by uakfdotb** [comment]
You need to install libgeoip, probably apt-get install libgeoip-dev depending on your OS.
