### ISSUE TITLE
Not a issue

### ISSUE THREAD

**Issue by styla01** [uakfdotb/ent-ghost#16]
Hi Uakf and Arty!

Now with 1.29 patch, I saw the bot is longer updated here in git. If is possible, my question is if I can get read access to the ENT  bitbucket repo. My ID is same for both, git and bitbucket.
Thank you mates.

**Comment by uakfdotb** [comment]
Code is not public anymore. You can apply this commit to the source:

https://github.com/uakfdotb/ghostpp/commit/44e3e44033a523f3b30880bbe5d741b89ab45558

**Comment by styla01** [comment]
thank you mate
