### ISSUE TITLE
I have problem

### ISSUE THREAD

**Issue by PrOGm2** [uakfdotb/ent-ghost#2]
string CSocket :: GetHostName( )
{
    if( m_CachedHostName.empty( ) )
    {
        char host[NI_MAXHOST], service[NI_MAXSERV];
        int s = getnameinfo( ( struct sockaddr \* ) &m_SIN, sizeof( m_SIN ), host, NI_MAXHOST, service, NI_MAXSERV, NI_NUMERICSERV );
        string str( host );

```
    m_CachedHostName = str;

    if( m_CachedHostName.empty( ) )
        m_CachedHostName = "Unknown";

    return str;
}
else
    return m_CachedHostName;
```

}

What should I do??

2>.\socket.cpp(161) : error C2065: 'NI_MAXHOST' : undeclared identifier
2>.\socket.cpp(161) : error C2065: 'NI_MAXSERV' : undeclared identifier
2>.\socket.cpp(162) : error C2065: 'NI_MAXHOST' : undeclared identifier
2>.\socket.cpp(162) : error C2065: 'NI_MAXSERV' : undeclared identifier
2>.\socket.cpp(162) : error C2065: 'NI_NUMERICSERV' : undeclared identifier
2>.\socket.cpp(162) : error C3861: 'getnameinfo': identifier not found

**Comment by uakfdotb** [comment]
The code is designed for Linux systems. Are you using Windows? You may need to #include <winsock2.h>

**Comment by PrOGm2** [comment]
Yes i use windows, what should i do??

**Comment by uakfdotb** [comment]
For some reason last comment got cut off I think. Try

#include winsock.h

**Comment by PrOGm2** [comment]
Where should i put this??
