### ISSUE TITLE
install.sql / table bans

### ISSUE THREAD

**Issue by Kreutertee** [uakfdotb/ent-ghost#4]
I stumbled upon a weird default MySQL behaviour. 

http://dev.mysql.com/doc/refman/5.7/en/data-type-defaults.html (all MySQL version 5.0-5.7)
"Otherwise, for the first TIMESTAMP column in a table, the default value is the current date and time." 

But the `date` column has not only DEFAULT CURRENT_TIMESTAMP (which would be ok) but also ON UPDATE CURRENT_TIMESTAMP (which is not ok imo)

This means for any update in the bans table, the `date` column is updated to the current date and time, which is nuts.

So changing to
`date` TIMESTAMP NOT NULL DEFAULT 0,
or
`date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

should do the trick.

edit: applies to all tables/columns with type TIMESTAMP where this shouldn't happen.

**Comment by uakfdotb** [comment]
Should be fixed.
