### ISSUE TITLE
To uakfdotb

### ISSUE THREAD

**Issue by Profforgr** [uakfdotb/ent-ghost#5]
Hi uakfdotb.

I am sorry to post there. It sucks that github don't have build-in tool to reach user. Simply purge it after read.

Can you contact codelain.com owner to fix website issue? I assume that he is not in place / don't know about the problem? Or he don't know how to fix something?

I hope you'll read it there since your last commit goes to that repo :)

**Comment by uakfdotb** [comment]
I emailed leax at admin@codelain.com or something like that but never got a response.
