### ISSUE TITLE
error make 

### ISSUE THREAD

**Issue by TemKaSD** [uakfdotb/ent-ghost#8]
ent-ghost-luna$ make clean && make
rm -f bncsutilinterface.o bnet.o bnetprotocol.o bnlsclient.o bnlsprotocol.o commandpacket.o config.o crc32.o csvparser.o game.o game_base.o gameplayer.o gameprotocol.o gameslot.o gcbiprotocol.o ghost.o ghostdb.o ghostdbmysql.o gpsprotocol.o language.o map.o packed.o replay.o savegame.o sha1.o socket.o stats.o statsdota.o statsw3mmd.o util.o  ./ghost++
g++ -o bncsutilinterface.o  -O3 -g -DBOOST_FILESYSTEM_VERSION=2 -I. -I../bncsutil/src/ -I../StormLib/ -c bncsutilinterface.cpp
In file included from ghost.h:29:0,
                 from bncsutilinterface.cpp:26:
includes.h:51:19: fatal error: GeoIP.h: Нет такого файла или каталога
compilation terminated.
make: **\* [bncsutilinterface.o] Ошибка 1

**Comment by uakfdotb** [comment]
You are missing libgeoip

**Comment by TemKaSD** [comment]
Where can I get it?

**Comment by uakfdotb** [comment]
If you're on Debian/Ubuntu, apt-get install libgeoip-dev

Otherwise you can make && make install from https://github.com/maxmind/geoip-api-c/tree/master/libGeoIP

**Comment by TemKaSD** [comment]
/ent-ghost-luna$ make clean && make
rm -f bncsutilinterface.o bnet.o bnetprotocol.o bnlsclient.o bnlsprotocol.o commandpacket.o config.o crc32.o csvparser.o game.o game_base.o gameplayer.o gameprotocol.o gameslot.o gcbiprotocol.o ghost.o ghostdb.o ghostdbmysql.o gpsprotocol.o language.o map.o packed.o replay.o savegame.o sha1.o socket.o stats.o statsdota.o statsw3mmd.o util.o  ./ghost++
g++ -o bncsutilinterface.o  -O3 -g -DBOOST_FILESYSTEM_VERSION=2 -I. -I../bncsutil/src/ -I../StormLib/ -c bncsutilinterface.cpp
g++ -o bnet.o  -O3 -g -DBOOST_FILESYSTEM_VERSION=2 -I. -I../bncsutil/src/ -I../StormLib/ -c bnet.cpp
In file included from /usr/local/include/boost/filesystem.hpp:15:0,
                 from bnet.cpp:44:
/usr/local/include/boost/filesystem/config.hpp:16:5: error: #error Compiling Filesystem version 3 file with BOOST_FILESYSTEM_VERSION defined != 3
bnet.cpp: In member function ‘void CBNET::BotCommand(std::string, std::string, bool, bool)’:
bnet.cpp:1658:29: error: ‘class boost::filesystem::directory_entry’ has no member named ‘filename’
bnet.cpp:1659:39: error: conversion from ‘boost::filesystem::path’ to non-scalar type ‘std::string {aka std::basic_string<char>}’ requested
bnet.cpp:1669:31: error: ‘class boost::filesystem::directory_entry’ has no member named ‘filename’
bnet.cpp:1671:39: error: ‘class boost::filesystem::directory_entry’ has no member named ‘filename’
bnet.cpp:1687:42: error: conversion from ‘boost::filesystem::path’ to non-scalar type ‘std::string {aka std::basic_string<char>}’ requested
bnet.cpp:1769:29: error: ‘class boost::filesystem::directory_entry’ has no member named ‘filename’
bnet.cpp:1770:39: error: conversion from ‘boost::filesystem::path’ to non-scalar type ‘std::string {aka std::basic_string<char>}’ requested
bnet.cpp:1780:25: error: ‘class boost::filesystem::directory_entry’ has no member named ‘filename’
bnet.cpp:1782:33: error: ‘class boost::filesystem::directory_entry’ has no member named ‘filename’
bnet.cpp:1798:42: error: conversion from ‘boost::filesystem::path’ to non-scalar type ‘std::string {aka std::basic_string<char>}’ requested
make: **\* [bnet.o] Ошибка 1

**Comment by uakfdotb** [comment]
ent-ghost is designed to work with boost filesystem v2. You'll need to patch to v3 in order to use later versions of boost as v2 support was dropped.

**Comment by ajenkul** [comment]
86-cygwin32\egcs-2.91.57..........\include\boost/thread.hpp:13,
                 from includes.h:50,
                 from ghost.h:29,
                 from bncsutilinterface.cpp:26:
C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i586-cygwin32\egcs-2.91.
57..........\include\boost/static_assert.hpp:62: warning: invalid character
 in macro parameter name
C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i586-cygwin32\egcs-2.91.
57..........\include\boost/static_assert.hpp:62: badly punctuated parameter
 list in `#define'
C:\cygnus\cygwin-b20\H-i586-cygwin32\bin\..\lib\gcc-lib\i586-cygwin32\egcs-2.91.
57\..\..\..\..\..\include\boost/static_assert.hpp:170: warning: invalid characte
r in macro parameter name
C:\cygnus\cygwin-b20\H-i586-cygwin32\bin\..\lib\gcc-lib\i586-cygwin32\egcs-2.91.
57\..\..\..\..\..\include\boost/static_assert.hpp:170: badly punctuated paramete
r list in`#define'
In file included from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/thread/detail/thread.hpp:1
7,
                 from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/thread/thread_only.hpp:22,

```
             from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin\..\lib\gcc-lib\i5
```

86-cygwin32\egcs-2.91.57..........\include\boost/thread/thread.hpp:12,
                 from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/thread.hpp:13,
                 from includes.h:50,
                 from ghost.h:29,
                 from bncsutilinterface.cpp:26:
C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i586-cygwin32\egcs-2.91.
57..........\include\boost/thread/mutex.hpp:18: #error "Boost threads unava
ilable on this platform"
In file included from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/thread/detail/thread.hpp:2
1,
                 from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/thread/thread_only.hpp:22,

```
             from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin\..\lib\gcc-lib\i5
```

86-cygwin32\egcs-2.91.57..........\include\boost/thread/thread.hpp:12,
                 from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/thread.hpp:13,
                 from includes.h:50,
                 from ghost.h:29,
                 from bncsutilinterface.cpp:26:
C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i586-cygwin32\egcs-2.91.
57..........\include\boost/thread/detail/thread_heap_alloc.hpp:19: #error "
Boost threads unavailable on this platform"
In file included from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/thread/detail/thread.hpp:3
5,
                 from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/thread/thread_only.hpp:22,

```
             from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin\..\lib\gcc-lib\i5
```

86-cygwin32\egcs-2.91.57..........\include\boost/thread/thread.hpp:12,
                 from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/thread.hpp:13,
                 from includes.h:50,
                 from ghost.h:29,
                 from bncsutilinterface.cpp:26:
C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i586-cygwin32\egcs-2.91.
57..........\include\boost/io/ios_state.hpp:15: ios: No such file or direct
ory
C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i586-cygwin32\egcs-2.91.
57..........\include\boost/io/ios_state.hpp:19: ostream: No such file or di
rectory
C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i586-cygwin32\egcs-2.91.
57..........\include\boost/io/ios_state.hpp:20: streambuf: No such file or
directory
In file included from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/functional/hash/extensions
.hpp:22,
                 from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/functional/hash/hash.hpp:5
58,
                 from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/functional/hash.hpp:6,
                 from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/thread/detail/thread.hpp:3
8,
                 from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/thread/thread_only.hpp:22,

```
             from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin\..\lib\gcc-lib\i5
```

86-cygwin32\egcs-2.91.57..........\include\boost/thread/thread.hpp:12,
                 from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/thread.hpp:13,
                 from includes.h:50,
                 from ghost.h:29,
                 from bncsutilinterface.cpp:26:
C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i586-cygwin32\egcs-2.91.
57..........\include\boost/detail/container_fwd.hpp:109: bitset: No such fi
le or directory
In file included from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/chrono/system_clocks.hpp:6
2,
                 from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/thread/detail/thread.hpp:4
0,
                 from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/thread/thread_only.hpp:22,

```
             from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin\..\lib\gcc-lib\i5
```

86-cygwin32\egcs-2.91.57..........\include\boost/thread/thread.hpp:12,
                 from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/thread.hpp:13,
                 from includes.h:50,
                 from ghost.h:29,
                 from bncsutilinterface.cpp:26:
C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i586-cygwin32\egcs-2.91.
57..........\include\boost/chrono/duration.hpp:37: limits: No such file or
directory
In file included from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/chrono/duration.hpp:41,
                 from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/chrono/system_clocks.hpp:6
2,
                 from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/thread/detail/thread.hpp:4
0,
                 from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/thread/thread_only.hpp:22,

```
             from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin\..\lib\gcc-lib\i5
```

86-cygwin32\egcs-2.91.57..........\include\boost/thread/thread.hpp:12,
                 from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/thread.hpp:13,
                 from includes.h:50,
                 from ghost.h:29,
                 from bncsutilinterface.cpp:26:
C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i586-cygwin32\egcs-2.91.
57..........\include\boost/ratio/ratio.hpp:42: limits: No such file or dire
ctory
In file included from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/ratio/ratio.hpp:48,
                 from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/chrono/duration.hpp:41,
                 from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/chrono/system_clocks.hpp:6
2,
                 from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/thread/detail/thread.hpp:4
0,
                 from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/thread/thread_only.hpp:22,

```
             from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin\..\lib\gcc-lib\i5
```

86-cygwin32\egcs-2.91.57..........\include\boost/thread/thread.hpp:12,
                 from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/thread.hpp:13,
                 from includes.h:50,
                 from ghost.h:29,
                 from bncsutilinterface.cpp:26:
C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i586-cygwin32\egcs-2.91.
57..........\include\boost/ratio/detail/overflow_helpers.hpp:40: limits: No
 such file or directory
In file included from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/thread/v2/thread.hpp:14,
                 from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/thread/thread_only.hpp:26,

```
             from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin\..\lib\gcc-lib\i5
```

86-cygwin32\egcs-2.91.57..........\include\boost/thread/thread.hpp:12,
                 from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/thread.hpp:13,
                 from includes.h:50,
                 from ghost.h:29,
                 from bncsutilinterface.cpp:26:
C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i586-cygwin32\egcs-2.91.
57..........\include\boost/thread/condition_variable.hpp:18: #error "Boost
threads unavailable on this platform"
In file included from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/thread/detail/thread_group
.hpp:9,
                 from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/thread/thread.hpp:13,
                 from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/thread.hpp:13,
                 from includes.h:50,
                 from ghost.h:29,
                 from bncsutilinterface.cpp:26:
C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i586-cygwin32\egcs-2.91.
57..........\include\boost/thread/shared_mutex.hpp:24: #error "Boost thread
s unavailable on this platform"
In file included from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/thread.hpp:17,
                 from includes.h:50,
                 from ghost.h:29,
                 from bncsutilinterface.cpp:26:
C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i586-cygwin32\egcs-2.91.
57..........\include\boost/thread/once.hpp:25: #error "Boost threads unavai
lable on this platform"
In file included from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/thread.hpp:18,
                 from includes.h:50,
                 from ghost.h:29,
                 from bncsutilinterface.cpp:26:
C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i586-cygwin32\egcs-2.91.
57..........\include\boost/thread/recursive_mutex.hpp:18: #error "Boost thr
eads unavailable on this platform"
In file included from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/exception/to_string.hpp:16
,
                 from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/exception/to_string_stub.h
pp:15,
                 from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/exception/info.hpp:16,
                 from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/exception/detail/exception
_ptr.hpp:20,
                 from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/exception_ptr.hpp:9,
                 from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/thread/exceptional_ptr.hpp
:10,
                 from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/thread/future.hpp:21,
                 from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/thread.hpp:24,
                 from includes.h:50,
                 from ghost.h:29,
                 from bncsutilinterface.cpp:26:
C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i586-cygwin32\egcs-2.91.
57..........\include\boost/exception/detail/is_output_streamable.hpp:15: os
tream: No such file or directory
In file included from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/exception/to_string_stub.h
pp:16,
                 from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/exception/info.hpp:16,
                 from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/exception/detail/exception
_ptr.hpp:20,
                 from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/exception_ptr.hpp:9,
                 from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/thread/exceptional_ptr.hpp
:10,
                 from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/thread/future.hpp:21,
                 from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/thread.hpp:24,
                 from includes.h:50,
                 from ghost.h:29,
                 from bncsutilinterface.cpp:26:
C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i586-cygwin32\egcs-2.91.
57..........\include\boost/exception/detail/object_hex_dump.hpp:17: ios: No
 such file or directory
In file included from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/exception_ptr.hpp:9,
                 from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/thread/exceptional_ptr.hpp
:10,
                 from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/thread/future.hpp:21,
                 from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\boost/thread.hpp:24,
                 from includes.h:50,
                 from ghost.h:29,
                 from bncsutilinterface.cpp:26:
C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i586-cygwin32\egcs-2.91.
57..........\include\boost/exception/detail/exception_ptr.hpp:30: ios: No s
uch file or directory
In file included from C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i5
86-cygwin32\egcs-2.91.57..........\include\GeoIP.h:31,
                 from includes.h:51,
                 from ghost.h:29,
                 from bncsutilinterface.cpp:26:
C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i586-cygwin32\egcs-2.91.
57..........\include\g++\winsock2.h:126: warning: `FD_CLR' redefined
C:\cygnus\cygwin-b20\H-i586-cygwin32\bin\..\lib\gcc-lib\i586-cygwin32\egcs-2.91.
57\..\..\..\..\i586-cygwin32\include\sys/types.h:161: warning: this is the locat
ion of the previous definition
C:\cygnus\cygwin-b20\H-i586-cygwin32\bin\..\lib\gcc-lib\i586-cygwin32\egcs-2.91.
57\..\..\..\..\..\include\g++\winsock2.h:141: warning:`FD_SET' redefined
C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i586-cygwin32\egcs-2.91.
57........\i586-cygwin32\include\sys/types.h:160: warning: this is the locat
ion of the previous definition
C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i586-cygwin32\egcs-2.91.
57..........\include\g++\winsock2.h:143: warning: `FD_ZERO' redefined
C:\cygnus\cygwin-b20\H-i586-cygwin32\bin\..\lib\gcc-lib\i586-cygwin32\egcs-2.91.
57\..\..\..\..\i586-cygwin32\include\sys/types.h:163: warning: this is the locat
ion of the previous definition
C:\cygnus\cygwin-b20\H-i586-cygwin32\bin\..\lib\gcc-lib\i586-cygwin32\egcs-2.91.
57\..\..\..\..\..\include\g++\winsock2.h:145: warning:`FD_ISSET' redefined
C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i586-cygwin32\egcs-2.91.
57........\i586-cygwin32\include\sys/types.h:162: warning: this is the locat
ion of the previous definition
In file included from ..\bncsutil\src\bncsutil/bncsutil.h:29,
                 from bncsutilinterface.cpp:30:
..\bncsutil\src\bncsutil/mutil.h:30: warning: `LITTLEENDIAN' redefined
C:\cygnus\cygwin-b20\H-i586-cygwin32\bin..\lib\gcc-lib\i586-cygwin32\egcs-2.91.
57..........\include\g++\winsock2.h:1073: warning: this is the location of
the previous definition
make.exe: **\* [bncsutilinterface.o] Error 1

Please help me uakfdotb, I can't make this

**Comment by Profforgr** [comment]
ent-ghost is Linux only. For Windows use plain Ghost++.

**Comment by ajenkul** [comment]
Where to find Ghost++ source code ?

**Comment by Profforgr** [comment]
> Where to find Ghost++ source code ?

https://code.google.com/p/ghostplusplus/source/browse/#svn%2Ftrunk

**Comment by ajenkul** [comment]
That's very kind of you ^^. Thanks
